-- AlterTable
ALTER TABLE "MemoryCollection" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true;

-- CreateIndex
CREATE INDEX "MemoryCollection_userId_isAutoGenerated_idx" ON "MemoryCollection"("userId", "isAutoGenerated");
